[package]
name = "chip8_emu"
version = "0.1.0"
authors = ["Pramode <mail@pramode.in>"]

[dependencies]
maplit = "1.0.0"
lazy_static = "0.2.9"
rand = "0.3.18"
sdl2 = "0.31.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"

